version: "2.2"

networks:
    keycloak:
        ipam:
            config:
            - subnet: 10.0.1.0/24
            
services:
    
    mariadb:
        build: db/mariadb
        image: keycloak_test_mariadb:${KEYCLOAK_VERSION:-latest}
        cpus: 1
        networks:
            - keycloak
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: keycloak
            MYSQL_USER: keycloak
            MYSQL_PASSWORD: keycloak
            MYSQL_INITDB_SKIP_TZINFO: 1
        ports:
            - "3306:3306"
            
    keycloak:
        build: keycloak
        image: keycloak_test_keycloak:${KEYCLOAK_VERSION:-latest}
        depends_on:
            mariadb:
                condition: service_healthy
        cpus: 1
        networks:
            - keycloak
        environment:
            MARIADB_HOST: mariadb
            MARIADB_DATABASE: keycloak
            MARIADB_USER: keycloak
            MARIADB_PASSWORD: keycloak
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
            DS_MIN_POOL_SIZE: 10
            DS_MAX_POOL_SIZE: 100
            DS_POOL_PREFILL: "true"
            DS_PS_CACHE_SIZE: 100
            WORKER_IO_THREADS: 2
            WORKER_TASK_MAX_THREADS: 16
            HTTP_MAX_CONNECTIONS: 500
        ports:
            - "8080:8080"
